### ISSUE TITLE
Menu on the left realigns after click on menu item.

### ISSUE THREAD

**Issue by SanjanaB** [alex-shpak/hugo-book#24]
Hi,

If I click on menu item on the left, the entire page refreshes and the menu is scrolled to the top. It doesnot maintain the position of where it was clicked initially. This leads to a bad UX, where the user has to scroll again all the way down on the menu to go back the previous position. Kindly fix the issue.

**Comment by alex-shpak** [comment]
Hm, this one requires a bit of brainstorming.
Since site is generated as static files looks like there is no other option except scroll to link with JS.

Any ideas?

**Comment by SanjanaB** [comment]
We generate static files with the menu bar. Instead, if we have a template of menu which doesnot refresh and only the content section refreshes, this could solve the problem?

**Comment by alex-shpak** [comment]
Unfortunately it would not work like this for static site generator, where each page is a static html.
I pushed JS snippet yesterday, which saves scroll position and restores no load. you need to enable it with `BookEnableJS: true` since I keep it off by default

**Comment by SanjanaB** [comment]
I tried out the fix and the site flickers on every menu click.

**Comment by alex-shpak** [comment]
Flickering you mean menu get reset and scrolled to original position? Or just page reload.

**Comment by SanjanaB** [comment]
We have partially fixed it using jquery animate. However, random flickering happens when the scrollTop is set. I am testing it on chrome.

**Comment by SanjanaB** [comment]
`{{ define "jsmenu" }}
<script>
    (function() {
        var menu = document.querySelector('aside.book-menu nav')
        addEventListener('beforeunload', function(event) {
            localStorage.setItem('menu.scrollTop', menu.scrollTop)
        });
    })()
    var loadFunction = function(){
        var menu = document.querySelector('aside.book-menu nav')
        var top = parseInt(localStorage.getItem('menu.scrollTop'));
        $(menu).animate({
            scrollTop: top
        }, 10)
    }
    window.onload = loadFunction();
</script>
{{ end }}`

**Comment by alex-shpak** [comment]
I would prefer to not include JQuery into theme.
Probably there is no better solution because this is how static site generator works. Each time you click link browser loads new page.
